version: 1.0.{build}
image: Ubuntu
environment:
  ASPNETCORE_ENVIRONMENT: ci
stack: node 9, python 2.7, docker
services:
  - postgresql
  - docker
platform: Any CPU
configuration: Release
before_build:
  - sh: .\babysitter\before_build.sh
build_script:
  - sh: .\babysitter\build_script.sh
test_script:
  - sh: .\babysitter\test_script.sh
  
  