version: 1.0.{build}
image: Visual Studio 2017
environment:
  ASPNETCORE_ENVIRONMENT: ci
services:
  - postgresql
platform: Any CPU
configuration: Release
before_build:
  - ps: .\babysitter\before_build.ps1
build_script:
  - ps: .\babysitter\build_script.ps1
test_script:
  - ps: .\babysitter\test_script.ps1
  
  