version: 1.0.{build}
image: Visual Studio 2017
services:
  - postgresql
platform: Any CPU
configuration: Release
before_build:
  - ps: cd .\babysitter && dotnet restore
build_script:
  - ps: cd .\babysitter & & dotnet build --configuration Release
test_script:
  - ps: .\babysitter\test_script.ps1
  
  