// <auto-generated />
using BabySitter.Core.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BabySitter.Web.Migrations
{
    [DbContext(typeof(BabySitterContext))]
    [Migration("20180625200530_AddHourlyRatesToBabySitter")]
    partial class AddHourlyRatesToBabySitter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BabySitter.Core.Entities.BabySitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("HourlyRate");

                    b.Property<int>("HourlyRateAfterMidnight");

                    b.Property<int>("HourlyRateBetweenBedtimeAndMidnight");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("BabySitters");
                });
#pragma warning restore 612, 618
        }
    }
}
